name = "rpc-read-proxy"
main = "src/index.ts"
compatibility_date = "2024-12-30"

routes = [
  { pattern = "rpc.yearn.fi", custom_domain = true }
]

[observability]
[observability.logs]
enabled = true
invocation_logs = true
